[build]
builder = "NIXPACKS"

buildCommand = "rm -rf .next && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
